######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 18 12:12:18 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += aboutd.h \
           FuzzThread.h \
           Logger.h \
           mainwindow.h \
           networkmessages.h \
           Sockets.h \
           splashScreen.h \
           Threads.h \
           Timeval.h
FORMS += aboutd.ui mainwindow.ui
SOURCES += aboutd.cpp \
           FuzzThread.cpp \
           Logger.cpp \
           main.cpp \
           mainwindow.cpp \
           Sockets.cpp \
           splashScreen.cpp \
           Threads.cpp \
           Timeval.cpp
RESOURCES += img.qrc
